<?php
declare(strict_types=1);

namespace App\Extensions;

use Twig\Extension\AbstractExtension;
use Twig\TwigFunction;

/**
 * Twig extension for Vite asset resolution.
 * Reads the manifest.json generated by Vite to resolve hashed asset paths.
 */
class ViteTwigExtension extends AbstractExtension
{
    private ?array $manifest = null;
    private string $manifestPath;
    private string $basePath;

    public function __construct(string $basePath = '')
    {
        $this->basePath = rtrim($basePath, '/');
        // Remove /public suffix if present (for subdirectory installations)
        if (str_ends_with($this->basePath, '/public')) {
            $this->basePath = substr($this->basePath, 0, -7);
        }

        // Manifest is in public/assets/.vite/manifest.json (Vite 5.x default)
        $publicRoot = dirname(__DIR__, 2) . '/public';
        $this->manifestPath = $publicRoot . '/assets/.vite/manifest.json';
    }

    public function getFunctions(): array
    {
        return [
            new TwigFunction('vite_asset', [$this, 'getAssetPath']),
            new TwigFunction('vite_preload', [$this, 'getPreloadTags'], ['is_safe' => ['html']]),
        ];
    }

    /**
     * Get the resolved asset path from manifest.
     * Falls back to original path if manifest not found or entry missing.
     *
     * @param string $entry Entry name (e.g., 'resources/js/home.js' or 'js/home')
     * @return string Full URL path to the asset
     */
    public function getAssetPath(string $entry): string
    {
        $manifest = $this->loadManifest();

        if ($manifest === null) {
            // Fallback: No manifest, assume development or non-hashed build
            return $this->basePath . '/assets/' . $this->normalizeEntry($entry);
        }

        // Try exact match first
        if (isset($manifest[$entry])) {
            return $this->basePath . '/assets/' . $manifest[$entry]['file'];
        }

        // Try with resources/ prefix
        $resourcesEntry = 'resources/' . ltrim($entry, '/');
        if (isset($manifest[$resourcesEntry])) {
            return $this->basePath . '/assets/' . $manifest[$resourcesEntry]['file'];
        }

        // Try matching by name (for entries like 'js/home')
        foreach ($manifest as $key => $data) {
            $normalizedKey = $this->normalizeEntry($key);
            $normalizedEntry = $this->normalizeEntry($entry);
            if ($normalizedKey === $normalizedEntry) {
                return $this->basePath . '/assets/' . $data['file'];
            }
        }

        // Fallback: Return the entry as-is with assets prefix
        return $this->basePath . '/assets/' . $this->normalizeEntry($entry);
    }

    /**
     * Generate preload link tags for critical assets.
     *
     * @param array $entries Array of entry names to preload
     * @return string HTML preload tags
     */
    public function getPreloadTags(array $entries): string
    {
        $tags = [];
        foreach ($entries as $entry) {
            $path = $this->getAssetPath($entry);
            $ext = strtolower(pathinfo($path, PATHINFO_EXTENSION));

            if ($ext === 'js') {
                $tags[] = sprintf('<link rel="modulepreload" href="%s">', htmlspecialchars($path));
            } elseif ($ext === 'css') {
                $tags[] = sprintf('<link rel="preload" href="%s" as="style">', htmlspecialchars($path));
            }
        }
        return implode("\n    ", $tags);
    }

    /**
     * Load and cache the manifest file.
     */
    private function loadManifest(): ?array
    {
        if ($this->manifest !== null) {
            return $this->manifest;
        }

        if (!file_exists($this->manifestPath)) {
            return null;
        }

        $content = file_get_contents($this->manifestPath);
        if ($content === false) {
            return null;
        }

        $decoded = json_decode($content, true);
        if (!is_array($decoded)) {
            return null;
        }

        $this->manifest = $decoded;
        return $this->manifest;
    }

    /**
     * Normalize entry path for comparison.
     * Converts 'resources/js/home.js' to 'js/home.js'
     */
    private function normalizeEntry(string $entry): string
    {
        // Remove leading slash
        $entry = ltrim($entry, '/');

        // Remove resources/ prefix
        if (str_starts_with($entry, 'resources/')) {
            $entry = substr($entry, 10);
        }

        // Ensure .js extension for JS files without extension
        if (!str_contains($entry, '.') && str_starts_with($entry, 'js/')) {
            $entry .= '.js';
        }

        return $entry;
    }
}
